### ISSUE TITLE
Docs on how to run multiple trials simultaneously?

### ISSUE THREAD

**Issue by etrain** [hyperopt/hyperopt#192]
I'm trying to use hyperopt to optimize several items in parallel with an external process. It seems that the MongoTrials object was designed to make this possible, but the code/docs inside mongoexp.py seems to be stale. (e.g. still reference hyperopt-mongo-search which doesn't seem to exist anymore)

Is there a good example anywhere of how to get fmin to dump out a few example points to mongo instead of just one at a time? What about writing results back to mongo when a run is done?

Thanks!

**Comment by cuihenggang** [comment]
Hi, I have a similar question. I also hope to get a batch of suggestions to try, and then report their losses later. How do I do that?

I have figured out that I can get multiple suggestions with the tpe.suggest() function, but I couldn't figure out how to report back the loss. I think it probably has something to do with the "trials" argument passed to the tpe.suggest() function, but I don't know how to set it.

Do you have any insights on this?

Thank you!

**Comment by ved93** [comment]
I am trying to use parallelization using below link
https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB

But when I run 1000-5000 iteration, the time taken by hyperopt increases as compared to a single thread. Also while parallelizing, core uses doesn't increase. I am using 8 core AWS system.
Can you please help -
1. I am not sure if mongo trials are using parallelization or not. If not how can I do it?
2. I need to run several hyperopt program in parallel. How can I do it? It seems with mongo trials its not possible because mongo worker uses all the cores.

**Comment by ashay88** [comment]
I have created a pull request for this to re-enable _max_queue_len_ #417
