### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by xgdgsc** [hyperopt/hyperopt#237]
I noticed the version on pypi is quite old 0.0.2 that was released 2 years ago. Is new users recommended to use that release or current master? Do you plan on making any new release?

**Comment by jaberg** [comment]
Hi!

Yes, there have been a few bug fixes and possibly features added since the
pypi release. I'm not actively using/maintaining hyperopt these days.

If anyone would like to adopt the project at least temporarily and handle
e.g. the pypi release and a bit of testing beforehand, that would be a very
welcome contribution to the project.

- JB

**Comment by michaelmior** [comment]
You can follow [this milestone](https://github.com/hyperopt/hyperopt/milestone/3) for updates on the newest release.
