### ISSUE TITLE
Too low new tids with TPE Parallelisation

### ISSUE THREAD

**Issue by relue** [hyperopt/hyperopt#300]
Hello,

i am using a very high worker count and am using TPE. My Problem is that are not enough new jobs created, so the workers can be used. Is there a way to increase the amount of new jobs that TPE suggests? I tried to change the poll_interval_sec parameter in the constructor of FMinIter in fmin.py, but is doesnt increase the new suggestions.

It seems i get that much new jobs as the data download needs. So i get more when the download it fast, but I dont really unterstand this behaviour.

I get the following output from logging:
INFO:hyperopt.tpe:TPE using 30484/30484 trials with best loss 16313.965036
DEBUG:hyperopt.mongoexp:Refresh data download took 4.099293 seconds for 1 ids

Can one help with increasing the amount of jobs tpe creates?

Best Regards
Simon

**Comment by Pandoro** [comment]
I realize I'm a little late to the party, I just wanted to leave a little "me too". I also looked at the code a little and it seems that the real bottle neck is the generation of new trials based on all the given old trials. I didn't pin point it to which exact part was the slowest, but it also seemed to be correlated to how  responsiveness the database was.

Throughout the optimization it typically starts out with very few "new" trials so that by far not all workers are busy, but it will soon occupy all workers (~120 in my case, with trials taking between 1-2 minutes). But over the next few hours, only a fraction of the workers will remain busy, typically about 20 or so. Partially I can improve the load by running several experiments in parallel on one database, however, the problem still exists in the long run.

This is probably not an easy thing to fix, however, if you at some point refactor the code, this might be something to keep in mind.
