### ISSUE TITLE
How is hyperopt using main.py?

### ISSUE THREAD

**Issue by revantt** [hyperopt/hyperopt#422]
I was going through the code and found that no matter main.py is present or not my code ran perfectly so i was wondering what is the significance of main.py?

**Comment by maxpumperla** [comment]
Ah, finally a question with some context. As you see here, there were once scripts in "bin", which you see referenced in `main.py`.

https://github.com/hyperopt/hyperopt/commit/71b281d85e2bc2ab9f7f3027e4c753098b3173ce

 These scripts have since been moved to "hyperopt/scripts". The `hyperopt-search` script you see in the link above was using `main.py`, but has been removed.

@jaberg can we remove `main.py` or is this used somewhere else in the hyperopt ecosystem?

**Comment by maxpumperla** [comment]
I'm closing this. once we have feedback from @jaberg we might be able to remove it.
