### ISSUE TITLE
hp.choice() unexpected results

### ISSUE THREAD

**Issue by r0f1** [hyperopt/hyperopt#431]
Code:

```
from hyperopt import hp
from hyperopt import tpe
from hyperopt.fmin import fmin
from hyperopt import Trials

search_spaces = {
    'characters': hp.choice('characters', ["a", "b", "c", "d", "e", "f", "g"])
}

def objective(param):
    print(param)
    return 42

trials = Trials()
best = fmin(objective, search_spaces, tpe.suggest, max_evals=5, trials=trials)

print()
print(best)
```

Prints this result:

```
{'characters': 'e'}
{'characters': 'f'}
{'characters': 'f'}
{'characters': 'b'}
{'characters': 'g'}

{'characters': 4}
```

How come, that within the objective function I get a proper value for `characters` (that is, one character from the provided list of characters), but as output, called `best` here in this example, I get an index, rather than the character?

**Comment by bjkomer** [comment]
I don't remember the exact reasoning for why it's done this way, but I think it's related to the fact that `hp.choice` in the general case can have nested search spaces as elements. The actual parameter being chosen is the index rather than the value, since the value can still vary even when the parameter is fixed.

Take a look at #384 for ways to access the value itself. There is a `hyperopt.space_eval` function to do this.

Although the question still remains, should this be the default return value instead? It seems like it would be more intuitive than getting an index.

**Comment by maxpumperla** [comment]
see #463
