### ISSUE TITLE
Constructing Trials object from known data

### ISSUE THREAD

**Issue by tangoed2whiskey** [hyperopt/hyperopt#445]
Is it possible to manually construct a Trials object to represent previous hyperparameter/loss pairs that have been obtained in some way outside of hyperopt, or otherwise begin a hyperopt optimisation starting with some known data?

This would be a good way to, for example, include some analytically-known values into the optimisation without having to wait for them to be explicitly run.

**Comment by PhilipMay** [comment]
Hi @tangoed2whiskey ,
Maybe you want to have a look at this here: #267 

Here the Trials object gets pickled after an hyperopt run, unpickled and then the Hyperopt is getting restartet.
Instead of unpickle you could create the Trials object yourself.
The trials object is a bit weird but it should work. Just try it.
Maybe you could post your code here if it works. I would be interested.
