### ISSUE TITLE
Storing choice values by index instead of value?!

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#458]
Hi,
here I have a short demo with using `hp.choice`:
https://gist.github.com/PhilipMay/a3bea840669acfba8293291dfe438f54

Objective is being called with `'y': 'y1'` and `'y': 'y2'`. But the return value of `fmin` is not storing the value for `y`but the index as you can see after the link.

IMHO this is inconsistent and the consequence is that I can not use the result of fmin to call the objective function.

Would be great if someone could have a look into this. Although I am aware of the fast that changing this might be a breaking change...

Philip

**Comment by maxpumperla** [comment]
yeah, a lot of people stumble on this. we get recurring issues whose root cause is precisely this behaviour. I'd be very careful in changing this, though. As you said, it's a breaking change and we might do more harm than good.

Any ideas on how to pull this off by keeping backward compatibility? Maybe have a switch `return_indices` which is `True` by default and that you can turn off to return values? The problem with this is that it will be difficult to convey this new concept. How would we document this well enough and let people know?

**Comment by maxpumperla** [comment]
Don't think so, but we can and should test it.

**Comment by FlorisHoogenboom** [comment]
Wouldn't it be as simple to reuse the `return_agmin` argument in `fmin` ? This defaults to `True`, and if set otherwise nothing is returned by `fmin`. Wouldn't it be possible to simply return the value of `space_eval` called with the `argmin` found?

If you agree with this I would be more than happy to prepare a PR for this.

**Comment by PhilipMay** [comment]
Here is a short summery of argmin:
```
    argmin : None or dictionary
        If `return_argmin` is False, this function returns nothing.
        Otherwise, it returns `trials.argmin`.  This argmin can be converted
        to a point in the configuration space by calling
        `hyperopt.space_eval(space, best_vals)`.
```

To me this somehow sounds very weird because `trials.argmin` should already be the point in configuration space. There should be no need to convert it again. But this might be the solution to my "problem". At least it is mentioned in the docstring.

**Comment by FlorisHoogenboom** [comment]
I've make a PR since it is relatively simple to return the result of `space_eval` when `return_argmin` is set to `False`. This should be not that invasive since now it returns `None` in that case. Also, by default `return_agmin` is set to `True` so default behaviour won't change. This should resolve a lot of issues here.

**Comment by maxpumperla** [comment]
see #463
