### ISSUE TITLE
List parameters silently converted to tuples

### ISSUE THREAD

**Issue by Zahlii** [hyperopt/hyperopt#526]
![image](https://user-images.githubusercontent.com/218582/62774175-64cbee00-baa4-11e9-9b8a-090fdfcfe1b2.png)

Hyperopt silently changes lists definitions in a search space to tuples. While this is not difficult to circumvent, it is definitely NOT expected and cost me some hours to investigate the issue. Could this be changed or at least documented somewhere?

**Comment by AvisekNaug** [comment]
Today I am starting to use Hyperopt and discovered this issue!

**Comment by GiliR4t1qbit** [comment]
Just came across this surprising behaviour as well. 

Here's a textual example, similar to the above:
```
from hyperopt import hp
from hyperopt.pyll.stochastic import sample
space = hp.choice('a', [[0,1]])
sample(space)
```
which prints: `(0,1)` instead of the expected `[0,1]`.

**Comment by Apsylem** [comment]
Encountered this behaviour as well

**Comment by cwentland0** [comment]
I'm also seeing this.

**Comment by cwentland0** [comment]
After some (naive) digging, it seems the issue is coming from `pyll.base.pos_args(*args)`. When `pyll.base.rec_eval()` gets called during parameter space sampling, and in turn calls `rval = scope._impls[node.name](*args, **kwargs)`, apparently `node.name` is `"pos_args"` (implicitly calling `pyll.base.pos_args()`) and `args` is whatever the parameter's sampled value is. Since the entirety of the function `pyll.base.pos_args` is
```
@scope.define_pure
def pos_args(*args):
    return args
```
a list that gets passed via `*args` gets unpacked and returned as a tuple. Thus, any parameter space definitions which contain lists (e.g. the example given by @GiliR4t1qbit ) will result sampled parameters which are converted to tuples. It seems this behavior is recursive for nested lists, converting lists at every level to tuples. 

I am not an experienced Python developer in any capacity, nor do I understand the structure of Hyperopt, so I don't know a smart way to fix this. My application does rely on the distinction between tuple and list for handling edge cases in defining my neural network architectures, and this behavior breaks my application. If anyone can suggest a workaround, I would be incredibly appreciative.

**Comment by wenshanw** [comment]
Any updates on this issue?
