### ISSUE TITLE
All parameters not being returned correctly

### ISSUE THREAD

**Issue by Sanchita-P** [hyperopt/hyperopt#545]
Hi, I am using hyperopt for tuning my hyperparameters. Find below the space:

```
space = {
    'min_child_samples': hp.quniform('min_child_samples', 5, 100, 5), 
    'reg_alpha': hp.uniform('reg_alpha', 0.0, 1.0),
    'reg_lambda': hp.uniform('reg_lambda', 0.0, 1.0),
    'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 1.0),
    'max_depth' : hp.quniform('max_depth', 3, 10, 1),
    'subsample' : hp.quniform('subsample', 0.6, 1, 0.05),
    'num_leaves': hp.quniform('num_leaves', 20, 150, 1),  
    'subsample_freq': hp.quniform('subsample_freq',0,10,1),
    'min_gain_to_split': hp.quniform('min_gain_to_split', 0.01, 0.1, 0.01),

    'learning_rate' : 0.05,
    'objective' : 'binary'                                   
}

trials = Trials()
best = fmin(objective, space, algo=tpe.suggest, trials=trials, max_evals=10)
```

However, when I print best, there is no learning_rate or objective returned. Find below what is returned:
colsample_bytree': 0.7475063203723928,
 'max_depth': 4,
 'min_child_samples': 10,
 'min_gain_to_split': 0.07,
 'num_leaves': 128,
 'reg_alpha': 0.9290289501056285,
 'reg_lambda': 0.47598189121697,
 'subsample': 0.9,
 'subsample_freq': 1

Why are  learning_rate and objective not returned? Are they not even used in the hyperparameter tuning?

Thank you!

**Comment by bjkomer** [comment]
In your example, `learning_rate` and `objective` are set to fixed constants and will not be tuned. I'm guessing this is why they are not returned, because they are not treated as hyperparameters. They are given to your objective function, but they will not change from trial to trial.

If you want them to be used in tuning, you need to specify a domain to search over. Hyperopt has no idea what values are possible to choose until you do this. For your example, `objective` will likely use `hp.choice` and `learning_rate` could be `hp.loguniform`

**Comment by Sanchita-P** [comment]
Hi Brent! Thank you for your response. I did not want to tune these parameters, simply wanted to pass them as parameters to the model. If they're taken as parameters in my objective function, that works as well! Additionally, I used hp.choice and gave a list with just one value so that this value is returned as well.

**Comment by marctorrellas** [comment]
I was thinking about this trick when reading your first post. Yeah, a list with one element should work. Given that your "issue" can be solved @Sanchita-P , do you think the issue can be closed? :)

**Comment by maxpumperla** [comment]
https://hyperopt.github.io/hyperopt/ we have new docs here that potentially replace the wiki. you can send pull requests to the `docs` folder to help us improve it. I think we should have a FAQ section there, since the ever-present "wrong params returned" issue pops up what feels like every other week.

@bjkomer thanks for your help resolving this, btw

**Comment by Sanchita-P** [comment]
@marctorrellas and @maxpumperla apologies, for the delayed response. Yes, we can close this "issue"! @maxpumperla, noted. Also, yes - a FAQ section would make everyone's lives better :)
