### ISSUE TITLE
exact same point getting sampled in multiple trials by the tpe.suggest algorithm

### ISSUE THREAD

**Issue by ihadanny** [hyperopt/hyperopt#608]
related to #494 .
I'm using this space:
```python
ctb_reg_params = {
    'learning_rate':     hp.choice('learning_rate',     np.arange(0.01, 0.31, 0.01)),
    'max_depth':         hp.choice('max_depth',         np.arange(5, 16, 1, dtype=int)),
    'colsample_bylevel': hp.choice('colsample_bylevel', np.arange(0.3, 0.9, 0.1)),
    'l2_leaf_reg':      hp.choice('l2_leaf_reg',[1,3,5,10,100]),
    'border_count':      hp.choice('border_count',[32,5,10,20,50,100,200]),    
    'n_estimators':      500,
    'eval_metric':       'RMSE',
}
``` 

which is pretty big (~6K combinations).
after running `fmin(ctb_reg, space=ctb_para, trials=Trials(), algo=tpe.suggest, max_evals=500)`
I see in the results that 48 trials were used on the exact same combination (the best one) 9 trials on the second best combination, and the rest were repeated 2-3 times.
Is there a way to tell TPE not to waste time on running the exact same trial?

**Comment by bjkomer** [comment]
I'm not too familiar with the details of TPE, but I don't think something like that has been implemented yet. Definitely would be useful to have that option, picking the same best combination again may make sense for stochastic problems, but not for deterministic ones.

Did a quick scan through the code and the closest thing I can see to a parameter that may help with this is [`n_EI_candidates`](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L845). It looks like by default it picks chunks of 24 unique points based on the distribution it has built by past trials. Increasing this number will likely reduce duplicates.

Another workaround is to use `hp.uniform` or `hp.quniform` instead of `hp.choice`. By allowing fully continuous values to be chosen, you should never get the exact same combination chosen. E.g. instead of 48 trials being the exact same, there could be 48 very similar trials that are fine-tuning the best parameters. `choice` treats values as categorical, e.g. a max_depth of 5 would be considered equally distant to 6 as it would be to 16, which may not be what you intended.

**Comment by phyzhenli** [comment]
> 

Increasing the number of `n_EI_candidates` seems to not work for me...

**Comment by phyzhenli** [comment]
I 'solve' the problem by checking each call. If the current arguments are not in the trials, it will run. Otherwise it will return `STATUS_FAIL`. The `STATUS_FAIL` does not affect tpe. Here is the code (modified by #450):
```
import numpy as np
from hyperopt import fmin, tpe, mix, hp, STATUS_OK, STATUS_FAIL, Trials
from hyperopt import space_eval
from matplotlib import pyplot as plt
import seaborn as sns; sns.set()
from functools import partial

LOW, HIGH = -1000, 1000

def objective(x, trials, space):
    repeat = 0
    for t in trials:
        if t['result']['status'] == STATUS_OK:
            vals = t["misc"]["vals"]
            rval = {}
            for k, v in list(vals.items()):
                if v:
                    rval[k] = v[0]
            if x == space_eval(space, rval):
                repeat += 1

    if repeat >= 1:
        return {
            'status': STATUS_FAIL
        }
    else:
        return {
            'loss': x ** 2,
            'status': STATUS_OK,
            }


if __name__ == "__main__":
    trials = Trials()
    iterations = 600
    suggest_number = 20
    plot_initial_points = True
    space = hp.quniform('x', LOW, HIGH, 1)

    fmin(
        partial(objective, trials=trials, space=space),
        space=space,
        algo=tpe.suggest,
        # algo=partial(mix.suggest, p_suggest=[(0.25, rand.suggest), (0.75, tpe.suggest)]),
        max_evals=iterations,
        trials=trials,
    )

    counter_OK =0
    counter_FAIL = 0
    points_OK = []
    losses_OK = []
    for trial in trials:
        print(trial)
        vals = trial["misc"]["vals"]
        rval = {}
        for k, v in list(vals.items()):
            if v:
                rval[k] = v[0]
        if trial['result']['status'] == STATUS_OK:
            counter_OK += 1
            points_OK.append(int(space_eval(space, rval)))
            losses_OK.append(trial['result']['loss'])
        elif trial['result']['status'] == STATUS_FAIL:
            counter_FAIL += 1
    print('STATUS_OK: ', counter_OK, 'STATUS_FAIL: ', counter_FAIL)

    # get the initial data
    initial_points = points_OK[:counter_OK-suggest_number]
    initial_losses = losses_OK[:counter_OK-suggest_number]
    initial_plot_data = np.asarray(sorted(zip(initial_points, initial_losses)))

    # get the suggest data
    tpe_suggest_points = points_OK[counter_OK-suggest_number:]
    tpe_suggest_losses = losses_OK[counter_OK-suggest_number:]
    tpe_suggest_plot_data = np.asarray(sorted(zip(tpe_suggest_points, tpe_suggest_losses)))

    fig = plt.figure()
    ax = fig.add_subplot(111)

    # plot the objective fn
    temp = np.linspace(LOW, HIGH, 1000)
    ax.plot(temp, [x**2 for x in temp])

    # plot the initial values
    if plot_initial_points:
        ax.plot(initial_plot_data[:, 0], initial_plot_data[:, 1], marker='o', ls='', color='gray' )

    # plot the suggest trial values
    ax.plot(tpe_suggest_plot_data[:, 0], tpe_suggest_plot_data[:, 1], 'ro')

    # extend the y axis so that nothing gets cut off
    ax.set_ylim(bottom=-3)
    ax.set_title('max_evals=%d' % (iterations,))
    plt.show()
```

Outputs: STATUS_OK:  478      STATUS_FAIL:  122.
![Figure](https://user-images.githubusercontent.com/48823046/198328145-dfe2265f-9dc9-4df4-ad0e-318f2c9f417e.png)
