### ISSUE TITLE
Dependency between iterations

### ISSUE THREAD

**Issue by shaddyab** [hyperopt/hyperopt#610]
Are sequential fmin iterations independent from each other (i.e., the optimized hyperparameters in iteration number 2 are generated independently from the optimized hyperparameters generated in iteration number 1), or they are depending on each other ( i.e, the optimized hyperparameters in iteration number 2 are improving the the optimized hyperparameters generated in iteration number 1)?

**Comment by adalrsjr1** [comment]
As far as I know, In any Bayesian Optimization there is such kind of dependency between iterations. This happen due to the acquisition function (EI in hyperopt) that samples the next set of values based on previous in order to explore or exploit the search space. You can learn more about [here](https://distill.pub/2020/bayesian-optimization/).

**Comment by shaddyab** [comment]
@adalrsjr1 This is the same conclusion I reached after doing my own research. Thank you!
