### ISSUE TITLE
Can hyperopt deal with noise?

### ISSUE THREAD

**Issue by thomasahle** [hyperopt/hyperopt#618]
I'm trying to optimize a noisy function, like the following over [-1, 1]:

    def fun(x):
        return int(random.random() <= x**2)

I run

    fmin(fn=fun, space=hp.uniform('x',-1,1), algo=tpe.suggest, max_evals=1000)

but even with very large max_evals, it never seems to find the optimal `x` (0).
Is there a way to make hyperopt handle such noisy functions? Or is that out of scope?

**Comment by lismanown** [comment]
Same use case here, have you found any solution?

**Comment by thomasahle** [comment]
@lismanown No :-(
I eventually gave up the entire project of trying to do noisy optimization with Gaussian processes. I still think it should be possible, but I couldn't make it work with any library.
If you succeed, please let me know, so I can resume my original project.

**Comment by lismanown** [comment]
@thomasahle I found a potential solution, still haven't tried yet, but it looks promising, which is when hyperopt chooses a combination of hyperparameters to run, you run it multiple times until you get a good estimation of the mean output, and only return to hyperopt a reasonably good and low noisy estimate
So then it comes the question of how many times is enough, and one way to do it would be with bernstein’s inequality:

![image](https://user-images.githubusercontent.com/69450272/92335367-c1fdee80-f06c-11ea-98b2-ae28f2b04a7c.png)
 
Treating the result of the optimization with such hyperparameters as a random variable, with that formula you can get lets say 95% confidence that the mean is between a value _epsilon_ that you would choose. You would then keep running the process multiple times with the same hyperparameters until you are confident in that value and can return it to hyperopt. This way hyperopt will still have to deal with noise but it would not be as much as before. And good thing is you can adjust how confident you want to be when you return the value to hyperopt. 

I've tried the formula and it works great, if the output of your program follows a normal distribution and is bounded (not infinite). I had this idea of reducing the noise passed to hyperopt, but having only basic knowledge of statistics it took me quite some time to find how to do it the proper way, instead of just picking a random number, lets say 30, and run 30 times every time before returning the result to hyperopt, because you don't know how good it is. This seems such a common use case that these bernstein’s inequality and maybe other stuff should be integrated in frameworks or scientific libraries like hyperopt or scipy for example. I don't know, maybe someone more knowledgeable than me can give their perspective

**Comment by lismanown** [comment]
Happy to say it works much better this way, in the example below the optimization for `objective_with_confidence` is much more consistent than optimizing `objective` alone, provided the same computational power in my experience

```
def bernstein(samples, eps, max):
    mean = np.mean(samples)
    centered = samples - mean
    std = np.std(centered, ddof=1)
    n = len(samples)
    prob = math.exp(-(n * (eps ** 2)) / (2 * (std ** 2) + 2 * max * eps / 3))
    return prob

def objective(x):
    return cos(x * random.uniform(0, 1)) * random.uniform(0, 1) #min = -4.4 and 4.4

def objective_with_confidence(args):
    samples = [objective(args) for i in range(30)]
    std = np.std(samples)
    if std == 0:
        return {
            'status': STATUS_OK,
            'loss': np.mean(samples),
            'loss_variance': std
        }
    eps = 0.1 * std
    prob = bernstein(samples, eps, std * 7)
    while (prob > 0.05):
        samples.append(objective(args))
        prob = bernstein(samples, eps, std * 7)
    return {
        'status': STATUS_OK,
        'loss': np.mean(samples),
        'loss_variance': np.std(samples)
    }
```

**Comment by thomasahle** [comment]
The problem with this method is that if your target function is expensive, you probably don't want to run it a large number of times with the same parameters. At least that's what my users told me. It felt inefficient to not try some surrounding values instead.

**Comment by lismanown** [comment]
If the output is noisy and you run with other surrounding values and you get wildly different results, how do you know if its because of the slight change of values (some functions might be very sensitive) or its just the noise? There is no way around that IMO, it seems inherent to the problem. Given a set of parameters, one would want to try to eliminate the noise so the optimization algorithm can do its job assuming no or low noise. How costly that would be depends on how much noise there is. Using the Bernstein’s inequality, the less the std dev of the outputs, the less iterations you need to run with the same parameters to get a confident mean value. It feels like something like this could be integrated into the library, so ideally hyperopt should be able to detect and eliminate noise somehow, but that other statistical method on top of hyperopt does the trick for me. Right now I'm letting hyperopt only focus on figuring out the optimization function. It would be cool if the devs could give their view on this.

**Comment by cjmcgill** [comment]
@lismanown how did you find this method? Is there a textbook or a paper anywhere that talks about it? Did it work well for you in the intervening two years?
