### ISSUE TITLE
generate_trials_to_calculate breaks hyperopt when using conditional parameters

### ISSUE THREAD

**Issue by ekerazha** [hyperopt/hyperopt#646]
When I use `generate_trials_to_calculate` to suggest trials, after 20 evals I get an error with "nested" parameters such as:

`max_delta_step': hp.choice('max_delta_step', [0.0, hp.loguniform('max_delta_step_positive', -7, 4)]),`

I get errors like this:

```
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\base.py", line 686, in fmin
    show_progressbar=show_progressbar,
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\fmin.py", line 509, in fmin
    rval.exhaust()
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\fmin.py", line 266, in run
    new_ids, self.domain, trials, self.rstate.randint(2 ** 31 - 1)
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\tpe.py", line 932, in suggest
    [doc["misc"] for doc in docs], keys=list(domain.params.keys())
  File "C:\Users\xxx\miniconda3\lib\site-packages\hyperopt\base.py", line 208, in miscs_to_idxs_vals
    t_idxs = misc["idxs"][node_id]
KeyError: 'max_delta_step_positive'
```

**Comment by ekerazha** [comment]
The problem seems to be that it looks for the "max_delta_step_positive" parameter, but there's no such parameter when the "max_delta_step" choice is 0 (we only have "max_delta_step_positive" when the choice is 1).

**Comment by ekerazha** [comment]
I can apparently workaround this issue by creating a "dummy" parameter such as `'max_delta_step_positive': 1` also when the "max_delta_step" choice is 0. I don't know if this has some bad side effects.

**Comment by himanshurawlani** [comment]
> I can apparently workaround this issue by creating a "dummy" parameter such as `'max_delta_step_positive': 1` also when the "max_delta_step" choice is 0. I don't know if this has some bad side effects.

Can you please elaborate? How did you implement the workaround syntactically? I too have a nested parameter space like this:
```
"use_contrast": hp.choice("use_contrast", [
                            ("True", hp.choice('contrast_factor', [0.1, 0.2, 0.3, 0.4])),
                            ("False",)
                        ]
                    )

```
And I'm getting `KeyError: 'contrast_factor'`

**Comment by nirtsuk** [comment]
I also got "KeyError" and the problem was that I had to delete the "trials_save_file" (bin file) that saved my previous state since I changed the parameters.

**Comment by marcietran** [comment]
I also had some confusion about how to use `generate_trials_to_calculate`, and I think this function needs more documentation on usage. I assumed that each point in the `points` argument should look like an evaluated point of the search space and match the format of the params arg that's used in the objective function, but that's not the case. Each point should actually look something like what you get from `trials.argmin`, where for each `hp.choice` parameter, we have the index of the choice value instead of the actual value and the the keys are the labels for the hyperopt params

Hopefully this example helps clear things up for others:

```python
import hyperopt
from hyperopt import hp
from hyperopt.fmin import generate_trials_to_calculate

def objective(params):
    # dummy loss function for this example
    print(params)
    return {'loss': 1, 'status': hyperopt.STATUS_OK}

search_space = {
    "use_contrast": hp.choice("use_contrast_label", [
        (True, hp.choice('contrast_factor_label', [0.1, 0.2, 0.3, 0.4])),
        (False)
    ]),
    "param_2": hp.quniform("param_2_label", 0, 1, 0.1)
}

params_to_test = [
    # The objective function params arg will look like: {'param_2': 0.2, 'use_contrast': (True, 0.2)}
    {"use_contrast_label": 0,
     "contrast_factor_label": 1,
     "param_2_label": 0.2},
    # The objective function params arg will look like {'param_2': 0.9, 'use_contrast: False}
    {"use_contrast_label": 1,
     "constrast_factor_label": None,
     "param_2_label": 0.9}
]

trials = generate_trials_to_calculate(params_to_test)

hyperopt.fmin(
    fn=objective,
    space=search_space,
    algo=hyperopt.tpe.suggest,
    trials=trials,
    max_evals=1
)
```

**Comment by driscoll42** [comment]
marcietran's post helped me quite a bit but I needed to play a bit more to understand it. For anyone else who kept getting an error of "IndexError: list index out of range" when trying to run this, suppose you have the code below:

```
search_space = {
    "param_1": hp.choice('param_1_label', [4, 9]),
    "param_2": hp.quniform("param_2_label", 0, 1, 0.1)
}

params_to_test = [
    # The objective function params arg will look like: {'param_2': 0.2, 'use_contrast': (True, 0.2)}
    {"param_1_label": 9,
     "param_2_label": 0.2},
    # The objective function params arg will look like {'param_2': 0.9, 'use_contrast: False}
    {"param_1_label": 4,
     "param_2_label": 0.9}
]
```

This will fail. The reason is that while you are trying to set param_1_label to use the value 9, it needs the *index* of 1 passed to it. Similar that 4 shoudl use the index of 0. The correct code would be:

```
search_space = {
    "param_1": hp.choice('param_1_label', [4, 9]),
    "param_2": hp.quniform("param_2_label", 0, 1, 0.1)
}

params_to_test = [
    # The objective function params arg will look like: {'param_2': 0.2, 'use_contrast': (True, 0.2)}
    {"param_1_label": 1,
     "param_2_label": 0.2},
    # The objective function params arg will look like {'param_2': 0.9, 'use_contrast: False}
    {"param_1_label": 0,
     "param_2_label": 0.9}
]
```

Which seems counterintuitive to me and we should be able to pass values in directly as output by hyperopt, but this is something that works.
