### ISSUE TITLE
Where is the tree structure implementation in TPE?

### ISSUE THREAD

**Issue by QuetzalcoatlRosso** [hyperopt/hyperopt#658]
Hello, could someone point me to the code that represents the configuration space as a "tree-like structure" or perhaps the code on how 'dtree' is used in this [example](https://github.com/hyperopt/hyperopt/wiki/FMin#22-a-search-space-example-scikit-learn)? For the latter, it's unclear (to me) what entropy is being computed and how the root node of the (decision?) tree is determined. Thanks for your help!

**Comment by bjkomer** [comment]
This looks to be the part of the code where TPE uses the tree-like structure of the configuration space, in [tpe.py](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L662). Definitely not the easiest code to follow though.

The hyperparameter space is a tree-like structure because of choice points and nested hyperparameters. The example you linked to is showing one such structure for a couple sklearn classifiers (it could be a decision tree, or it could not be, that is a hyperparameter). This is what the objective function for that search space might look like:

```python
def objective(params):
    if params['type'] == 'naive_bayes':
        clf = sklearn.naive_bayes.GaussianNB()
    elif params['type'] == 'svm':
        clf = sklearn.svm.svc(
            c=params['c'],
            kernel=params['ktype'],
            # etc
        )
    elif params['type'] == 'dtree':
        clf = sklearn.tree.DecisionTreeClassifier(
            criterion=params['criterion'],
            # etc
        )

    clf.fit(X_train, y_train)
    loss = 1 - clf.score(X_test, y_test)
    return {'loss': loss, 'status':STATUS_OK}
```

**Comment by QuetzalcoatlRosso** [comment]
@bjkomer : Excellent, thank you. The [tpe.py](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L662) link is very useful, especially the build_posterior method.
