### ISSUE TITLE
how to print parameter space?

### ISSUE THREAD

**Issue by statcom** [hyperopt/hyperopt#673]
I would like to simply print the following parameter space. 

    hparam_space = { "batch_size": hp.choice('batch_size', [16, 32]) }

But print(hparam_space) resulted in

    Params testing:  {'batch_size': <hyperopt.pyll.base.Apply object at 0x000002753725E848>}

I've already tried to make it to json with  `json.dumps(params)` but I got the following error.

    TypeError: Object of type Apply is not JSON serializable

**Comment by bjkomer** [comment]
Currently the [Apply](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/pyll/base.py#L231) object only has a `__str__` function defined, looks like nested objects use `__repr__` instead.
If you print the object directly, you'll get something like this:
```Python
print(hparam_space['batch_size'])
#0 switch
#1   hyperopt_param
#2     Literal{batch_size}
#3     randint
#4       Literal{2}
#5   Literal{16}
#6   Literal{32}
```
Which is all the information that defines the parameter space. You'll have to map a `str()` call across the lists/dicts that contain your parameter spaces to get this information out.
It may be useful for someone to implement a different `__repr__` method, but since the spaces can be arbitrarily complex and nested, it may end up being a lot less readable than giving the object name.

**Comment by statcom** [comment]
As you suggested, the following simple function does the work

```
def print_hopt_space(hparam, file=None):
    print("Hyperparams testing:")
    for str in hparam:
        print(f'{str}:', file=file)
        print(f'{hparam[str]}', file=file)

```

It's not exactly what I wanted but I can live with it. 

Thanks for prompt answer as always!
