### ISSUE TITLE
Feature request: Use Spark's Fair scheduling mode to enable multiple parallel runs of SparkML jobs

### ISSUE THREAD

**Issue by tnixon** [hyperopt/hyperopt#717]
Currently, SparkTrials only works to distribute single-node frameworks across a spark cluster. However, using the [Fair scheduling mode](https://spark.apache.org/docs/latest/job-scheduling.html#scheduling-within-an-application), it should be possible to launch multiple trials for parallelized frameworks (such as SparkML) across a cluster. This could enable overall more efficient search for models being fit across very large datasets that cannot be trained on any single node.

**Comment by marctorsoc** [comment]
we don't have enough developers to support feature requests. I'm very happy to review a PR about this with a PoC, start from there and help getting it to the finish line :)

**Comment by maxpumperla** [comment]
@mengxr @liangz1 what do you guys think about that? should be beneficial to databricks as well, no?

**Comment by tnixon** [comment]
I understand, @marctorsoc, if I get time I may work on a PR for this. If others get to it before me, all the better. 

Another thought on this would be a new subtype of `Trials` that runs in parallel as separate threads/processes. This could be used to then spawn multiple Spark jobs on the driver node (fair scheduling or not) for multiple parallel SparkML or Horovod type jobs. It would double, however, as a way to parallelize hopt searches in non-Spark contexts as well.

**Comment by mengxr** [comment]
@tnixon It is certainly confusing that SparkTrials cannot run Spark jobs ... Maybe we can detect it and run it on the driver instead of shipping it to the worker. For now, user should use `Trials` for Spark jobs.

Running MLlib jobs in parallel might have downside on data locality. Most MLlib algorithm impl assumes data is cached. If there are concurrent jobs, tasks might not get scheduled to the node that contains the corresponding cached partition, which will trigger a data transfer. The trade-off is unclear.

Back to your request, if you set the schedule pool local property and then use `Trials` in async mode, it should work. Pay attention to this bug: https://issues.apache.org/jira/browse/SPARK-22340
