### ISSUE TITLE
Speed up with GPU and time taken per trial

### ISSUE THREAD

**Issue by zonexo** [hyperopt/hyperopt#732]
Hi,

I did a brief test and found that using GPU doesn't seem to be much difference in the speed. Is it supposed to be so?

Also, I found that as the test proceeds, my time taken per trial keeps increasing.  Is it supposed to be so?

Thanks.

**Comment by maxpumperla** [comment]
hey, I don't believe the GPU speedup part is a well-defined question. If you use model-based hparam optimization on heavy ML workloads that benefit from a GPU, then of course that speedup will dominate the rest, trial selection etc. is just a tiny part  of the equation. If you have smaller models, fast training iterations or use models that don't benefit from GPUs, you won't see an impact.

For the second part: do you put a lot of stuff in your trials? e.g. if you store the models itself, collecting info for trials might lead to a slow-down. but potentially there's a memory leak or so that we might have to look into, if you're onto something.

**Comment by zonexo** [comment]
ic ... I am doing optimization to get max value for my objective fn. So I'm just using the saved MLP model to do prediction and hyperopt will run it many times. I guess that's why there's no diff bet cpu and gpu.

for the 2nd part, I have 16 input parameters to vary, and hyperopt simply select a set of input parameters and predict the 5  outputs (output1 to output5). my obj is to get max output1. however, i also have constraints, like output2 > 0.85, output3 > 85 etc. if any of the constraints are not satisfied, i will set output1 as a very large number, and hence it'll be rejected by hyperopt.

but i thought this algorithm should take similar time per trial, so it doesn't make sense for the time per trial to increase after running 10000+ trials. I'll check using my cpu to see if it's the same.

**Comment by bjkomer** [comment]
If I recall correctly it is expected that an algorithm like `tpe` will take longer to run each trial as the number of trials increases because the computation to choose the next parameter depends on the number of previous parameters. The time it takes to run the objective itself should be the same, but the selection overhead will be larger. In contrast an algorithm like `rand` should be independent of the number of trials since it ignores the history.

**Comment by maxpumperla** [comment]
@bjkomer right, that's correct. I didn't know this was an issue in practice though. @zonexo usually your trials will be so computationally taxing that you can't (even remotely) afford 10k+ of them. It seems to me you run into mutually exclusive problems here, more or less, in the sense that experiments with 10k+ trials won't benefit from GPU as the underlying model is too small, or you'll just have a tiny fraction of those trials. Still, a very interesting observation and use case you have there.

**Comment by zonexo** [comment]
Ok I got it now. Thanks for the clarifications.
