### ISSUE TITLE
Can't retrieve best params from `fmin`

### ISSUE THREAD

**Issue by makquel** [hyperopt/hyperopt#746]
I've got a stacked pipeline that goes as follow: `Oversample -> Undersample -> XGboostClassifier`
I'm considering a search space as follows:

```python
search_space = {
    'xgb': {
        'learning_rate':    hp.choice('learning_rate', np.arange(0.05, 0.2, 0.05,dtype=float)),
        'max_depth':        hp.choice('max_depth',     np.arange(1, 4, 1, dtype=int)),
        'gamma':            hp.choice('gamma',         np.arange(0.5, 2, 0.5, dtype=float)),
        'eta':              hp.choice('eta',[0.8]),
        'n_estimators':     hp.choice('n_estimators',  np.arange(10, 40, 10,dtype=int)),
        'reg_alpha':        hp.uniform('reg_alpha', 0.0, 1.0),
        'reg_lambda':       hp.uniform('reg_lambda', 0.0, 1.0),
        'nthread':          hp.choice('nthread',[4]),
        'seed':             hp.choice('seed',[SEED])
#         'subsample':        hp.uniform('subsample', 0.8, 1)
    },
    'over': {
        'sampling_strategy':hp.choice('o_sampling_strategy',np.arange(0.2,0.55,0.05, dtype=float)),
        'k_neighbors':      hp.choice('o_k_neighbors', np.arange(5, 10, 1, dtype=int)),
        'random_state':     hp.choice('o_random_state',[SEED])
    },
    'under': {
        'sampling_strategy':hp.choice('u_sampling_strategy',np.arange(0.5,0.75,0.05, dtype=float)),
        'random_state':     hp.choice('u_random_state',[SEED])
    }
}

```
Once I the search for optimal parameters has done, and call the `fmin` method I got an output that doesn't seem right:
```python
{'eta': 0,
 'gamma': 0,
 'learning_rate': 3,
 'max_depth': 1,
 'n_estimators': 1,
 'nthread': 0,
 'o_k_neighbors': 0,
 'o_random_state': 0,
 'o_sampling_strategy': 0,
 'reg_alpha': 0.09057008727946296,
 'reg_lambda': 0.9634831416436873,
 'seed': 0,
 'u_random_state': 0,
 'u_sampling_strategy': 0}
```
Any clue whether this is some kind of format problem?

**Comment by bjkomer** [comment]
If you are using `hp.choice` the output you get at the end will be the index of the best parameter value.

You can do the mapping yourself or use `space_eval` to convert it to the actual parameter values. For example:

```python
from hyperopt import fmin, tpe, hp, space_eval
space = hp.choice('a',
    [
        ('case 1', 1 + hp.lognormal('c1', 0, 1)),
        ('case 2', hp.uniform('c2', -10, 10))
    ])
best = fmin(objective, space, algo=tpe.suggest, max_evals=100)

print(best)
# -> {'a': 1, 'c2': 0.01420615366247227}
print(space_eval(space, best))
# -> ('case 2', 0.01420615366247227)
```

**Comment by makquel** [comment]
Thanks for the headsup, I didn't know whether those values were and index or a erratic format output. the `space_eval` should do the job.

**Comment by extrospective** [comment]
I was bitten by this same issue, and think that's this ticket could better explain why hp.choice() needs to return index, or consider some other options such as returning value or having a function like hp.uniform_discrete() which behaves like hp.uniform() but returns value.  

I am using hp.choice() so I can pass in an array or list of values, basically a uniform discrete list (e.g. np.arange(x,y)).

It feels inconsistent that hp.choice returns index of parameter and hp.uniform would return value.   I find myself wanting to have functionality similar to hp.uniform() but instead with discrete values, and hp.choice() seems to be the method to do that, and maybe because of other uses it was settled on the fact that fmin reports the optimal index rather than value.

An impact of this difference between hp.choice() and hp.uinform() is encountered if one takes the best dictionary returned from fmin (best=fmin(...)) and then calls a model with best.  For parameters which return their values, the underlying model can take the best dictionary, but for those which take index, they require translation from index to value.  Since these dictionary keys have the same name (such as max_depth), one can make a mistake easily.  I was fortunate to run into max_depth=0 a few times and then diagnose this issue, whereas with other parameters I might not have noticed because they were still valid options for random forest.

How can the interface support direct return of best values?

How can hyperopt avoid a situation where there is an obvious trap?   (best is a dictionary with the same keys, but the values are sometimes indices and sometimes values.)

**Comment by bjkomer** [comment]
@extrospective
One reason why an index is returned is because in general `hp.choice` can contain nested structures of other hyperparameter spaces of arbitrary complexity. Index is how the `Trials` object store the choice parameter, and by default `fmin` just returns the record from that object (by calling `trials.argmin` at the end). 

The interface does actually support the direct return of the best value (though the documentation can certainly be improved...). You can have `fmin` do the conversion for you by using `fmin(return_argmin=False)` and the 'best' returned will be after applying `space_eval`.

There is an option for a uniform discrete variable, use `hp.quniform` instead of `hp.uniform` (the 'q' is for 'quantized' and the three parameters are low, high, and q). Setting the q parameter (step size) to an integer will give you a discrete list of integers.

I hope that helps!
