### ISSUE TITLE
early_stop_fn doesn't work with SparkTrials

### ISSUE THREAD

**Issue by dnjiao** [hyperopt/hyperopt#808]
I am doing model tuning with Hyperopt using mlflow in Azure Databricks. It is a regression problem. Objective function looks like below:

```
def train(params): 
    with mlflow.start_run(nested=True, run_name=input_run_name):
      clf = LGBMRegressor(**params)
      skf = StratifiedKFold(n_splits=splits, shuffle=True, random_state=random_seed)
      rmse = []
      for train_index, test_index in skf.split(X, df['Over100']):
        X_train = X.iloc[train_index]
        X_test = X.iloc[test_index]
        y_train = y.iloc[train_index]
        y_test = y.iloc[test_index]
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        metrics = eval_metrics(y_pred, y_test)
        rmse.append(np.sqrt(mean_squared_error(y_test, y_pred)
      
      return {'loss': np.mean(rmse), 'status': STATUS_OK}
```
 I set the max_eval to 1000 but I want to early stop if loss doesn't change for 50 iterations.

```
spark_trials = SparkTrials(parallelism=4)
with mlflow.start_run(run_name=input_run_name):
  argmin = fmin(
    max_evals=1000,
    fn=train,
    space=search_space,
    algo=tpe.suggest,
    trials=spark_trials,
    early_stop_fn=no_progress_loss(50)
  )  
```

However I got the following error:
```
     20     def stop_fn(trials, best_loss=None, iteration_no_progress=0):
---> 21         new_loss = trials.trials[len(trials.trials) - 1]["result"]["loss"]
     22         if best_loss is None:
     23             return False, [new_loss, iteration_no_progress + 1]

KeyError: 'loss'
```
Loss is defined already in objective function, why is it still complaining?

**Comment by bsesar** [comment]
I got a similar error but I used atpe.suggest instead of tpe.suggest. Once I switched to tpe.suggest, my code worked. I think the ```KeyError: 'loss'``` happens when something goes wrong with the suggest algo and is not a problem in our code.

Perhaps the issue with your code is here is the ```early_stop_fn=no_progress_loss(50)``` line. Have you tried using ```early_stopping_rounds=50``` instead?

**Comment by ntopousis** [comment]
I also get this error using tpe.suggest

**Comment by ntopousis** [comment]
dude i've got you, so the issue is that the output from like the first round yields a dictionary that looks like this 

`{'state': 0, 'tid': 16, 'spec': None, 'result': {'status': 'new'}, 'misc': {'tid': 16, 'cmd': ('domain_attachment', 'FMinIter_Domain'), 'workdir': None, 'idxs': {'bagging_fraction': [16], 'feature_fraction': [16], 'learning_rate': [16], 'min_data_in_leaf': [16], 'num_iterations': [16], 'num_leaves': [16]}, 'vals': {'bagging_fraction': [0.5793588243935752], 'feature_fraction': [0.595531838169978], 'learning_rate': [0.050027274648700104], 'min_data_in_leaf': [2540.0], 'num_iterations': [190.0], 'num_leaves': [38.0]}}, 'exp_key': None, 'owner': None, 'version': 0, 'book_time': None, 'refresh_time': None}`

so the early_stop_fn looks at this dictionary for the ['result']['loss'] keys and doesn't find it. 

however, it's super easy to fix. here's a customized version that shouldn't have the same issue.

`def no_progress_loss_custom(iteration_stop_count=20, percent_increase=0.0):
    """
    Stop function that will stop after X iteration if the loss doesn't increase
    Parameters
    ----------
    iteration_stop_count: int
        search will stop if the loss doesn't improve after this number of iteration
    percent_increase: float
        allow this percentage of variation within iteration_stop_count.
        Early stop will be triggered if the data didn't change for more than this number
        after iteration_stop_count rounds
    """

    def stop_fn(trials, best_loss=None, iteration_no_progress=0):
        print(trials.trials[-1])
        if trials.trials[-1]["result"]["status"] == "new":
          return (False, [None, 0])
        new_loss = trials.trials[-1]["result"]["loss"]
        if best_loss is None:
            return False, [new_loss, iteration_no_progress + 1]
        best_loss_threshold = best_loss - abs(best_loss * (percent_increase / 100.0))
        if new_loss < best_loss_threshold:
            best_loss = new_loss
            iteration_no_progress = 0
        else:
            iteration_no_progress += 1
  
        return (
            iteration_no_progress >= iteration_stop_count,
            [best_loss, iteration_no_progress],
        )

    return stop_fn
` 

also here's a link to the original stopping function which looks very similar and has more logging: https://github.com/hyperopt/hyperopt/blob/master/hyperopt/early_stop.py#L7

**Comment by Ronanlfy** [comment]
Any update on this? seems that callback on this trials.trials[-1]["result"]["status"] doesnt refer to the finished trail

**Comment by jinseock95** [comment]
When I executed the code parallelistically in a spark environment, I also experienced the above error.
I solved it like the following

```
import logging

logger = logging.getLogger(__name__)

def no_progress_loss(iteration_stop_count=20, percent_increase=0.0):
    """
    Stop function that will stop after X iteration if the loss doesn't increase
    Parameters
    ----------
    iteration_stop_count: int
        search will stop if the loss doesn't improve after this number of iteration
    percent_increase: float
        allow this percentage of variation within iteration_stop_count.
        Early stop will be triggered if the data didn't change for more than this number
        after iteration_stop_count rounds
    """
    iteration_no_progress = 0
    def stop_fn(trials, best_loss=None, iteration_no_progress=0):
        
        # early_stop_fn doesn't work with SparkTrials #808' : https://github.com/hyperopt/hyperopt/issues/808
        if trials.trials[-1]["result"]["status"] == "new":
            return False, [None, 0]

        new_loss = trials.trials[len(trials.trials) - 1]["result"]["loss"]
        
        if best_loss is None:
            return False, [new_loss, iteration_no_progress]
        
        best_loss_threshold = best_loss - abs(best_loss * (percent_increase / 100.0))
        
        # when fitting fail, pass or +1
        if new_loss is None:
            pass
#             iteration_no_progress += 1

        
        elif new_loss < best_loss_threshold:   # new_loss 가 best_loss 보다 작으면 새로 시작
            best_loss = new_loss
            iteration_no_progress = 0
        else:
            iteration_no_progress += 1
            logger.debug(
                "No progress made: %d iteration on %d. best_loss=%.2f, best_loss_threshold=%.2f, new_loss=%.2f"
                % (
                    iteration_no_progress,
                    iteration_stop_count,
                    best_loss,
                    best_loss_threshold,
                    new_loss,
                )
            )

        return (
            iteration_no_progress >= iteration_stop_count,
            [best_loss, iteration_no_progress],
        )

    return stop_fn
```

**Comment by kylegilde** [comment]
I tried both of the proposed solutions with iteration_stop_count=1, and they don't seem to work.

**Comment by tibfab** [comment]
In case someone is still looking: The object trials.trials contains a list of all running trials and only those with status == ok have the result key loss and other metrics.
