### ISSUE TITLE
loguniform is different

### ISSUE THREAD

**Issue by imbalu007** [hyperopt/hyperopt#819]
There seems to be difference between the way loguniform is sampled from in Hyperopt and Scipy
### Hyperopt:
![image](https://user-images.githubusercontent.com/629329/138643206-d26adad9-d360-49af-a213-9321ac1c414f.png)
(https://github.com/hyperopt/hyperopt/blob/175148302b3611ee0dc6aca9438dc582e21c0d43/hyperopt/pyll/stochastic.py#L41)
### Scipy:
![image](https://user-images.githubusercontent.com/629329/138643307-4ff4a87b-f98b-4264-8b68-c9b41280d909.png)
(https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_continuous_distns.py#L7096)

It seems that these are two different functions (it is possible to sample Nan from scipy's version but not from Hyperopt's). From wiki, it looks like scipy's version is the correct one (https://en.wikipedia.org/wiki/Reciprocal_distribution).

Why is the function different in Hyperopt?

**Comment by rharish101** [comment]
They are equivalent. As per [the same Wikipedia article](https://en.wikipedia.org/wiki/Reciprocal_distribution#Relationship_to_Log-Uniform):
> A positive random variable X is log-uniformly distributed if the logarithm of X is uniform distributed,

Since the exponential is a monotone function, Hyperopt's implementation correctly samples from the log-uniform distribution. The only difference is that Hyperopt uses `high` for `log(b)` and `low` for `log(a)`.

**Comment by michaelmior** [comment]
This question seems to be answered, so closing this. Please reopen if you have further questions.
