### ISSUE TITLE
hp.choice is sampling with replacement

### ISSUE THREAD

**Issue by Este1le** [hyperopt/hyperopt#835]
I defined a search space based only on hp.choice. It is a finite search space (864 points). And I hope TPE can sample without replacement and cover the whole search space, which means `fmin` should finish at iteration 864. However, I found that TPE samples with replacement and would sample same hyperparameter settings many times. And it takes forever to cover the whole search space. Is there a way to modify the code, so that only the unevaluated points would be sampled at each iteration? I'm sharing my code as follows.
```
from hyperopt import hp, fmin, tpe, space_eval, Trials
space = {}
space['bpe'] = hp.choice('bpe', ['1000.0', '2000.0', '4000.0', '8000.0', '16000.0', '32000.0'])
space['num_layers'] = hp.choice('num_layers', ['1.0', '2.0', '4.0', '6.0'])
space['num_embed'] = hp.choice('num_embed', ['256.0', '512.0', '1024.0'])
space['num_hidden'] = hp.choice('num_hidden', ['1024.0', '2048.0'])
space['num_heads'] = hp.choice('num_heads', ['8.0', '16.0'])
space['learning_rate'] = hp.choice('learning_rate', ['0.0003', '0.0006', '0.001'])
trials = Trials()
best = fmin(objective,
            space = space,
            algo = tpe.suggest,
            trials = trials,
            pass_expr_memo_ctrl=True
)
```

**Comment by skylogic004** [comment]
I believe the sampling by replacement is intentional. The objective function may be noisy, so it can obtain a better estimate by re-running already-evaluated points (**someone please correct me if I'm wrong** -- I'm not super familiar with TPE, but from my understanding of Bayesian optimization I think this is generally how it works). 

Neural networks are inherently stochastic so this behavior would be desired unless you have taken measures to reduce the variance of the trained models. 

Regardless, you could force it to evaluate all 864 points by manually injecting these configurations into the trials object. I believe the `generate_trials_to_calculate` function can be used for this, see https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py (and search for "generate_trials_to_calculate" in the Issues -- people have talked about modifying and changing the Trials object).
